version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 10
    target-branch: dev
    groups:
      dev-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: "@vercel/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 10
    target-branch: dev
