// Batch 9: Final entries to reach 500 (30 entries)
module.exports = [
  // --- Remaining gap areas ---
  {
    id: "fin-no-escrow-for-critical-deposits",
    name: "No Escrow for Critical Deposits",
    risk_category: "financial",
    clause_type: "fin-escrow-arrangement",
    trigger: "High-value transaction requiring deposit without escrow arrangement",
    description: "Deposits paid directly to counterparty are at risk if counterparty becomes insolvent before performance.",
    severity: "high",
    likelihood: "occasional",
    impact: "Total loss of deposit on counterparty insolvency.",
    detection_guidance: "For deposits >EUR 100K, check for escrow arrangement with independent custodian and defined release conditions.",
    remediation: "Require escrow for deposits >EUR 100K: independent custodian, defined release conditions, interest allocation, and dispute hold mechanism.",
    real_world_impact: null
  },
  {
    id: "fin-no-cost-of-living-adjustment",
    name: "No Cost of Living Adjustment for Employment",
    risk_category: "financial",
    clause_type: "emp-bonus-discretion",
    trigger: "Employment contract without cost of living adjustment or salary review mechanism",
    description: "Without COLA or review mechanism, real wages decline over time leading to retention issues.",
    severity: "low",
    likelihood: "common",
    impact: "Real wage erosion leading to increased attrition and recruitment costs.",
    detection_guidance: "Check employment contracts for annual salary review mechanism, COLA adjustment, or performance-based increment process.",
    remediation: "Include annual salary review: minimum CPI adjustment, performance increment opportunity, and transparent review criteria.",
    real_world_impact: null
  },
  {
    id: "op-no-documentation-standards",
    name: "No Documentation Standards for Deliverables",
    risk_category: "operational",
    clause_type: "sla",
    trigger: "Service or development contract without documentation standards and delivery requirements",
    description: "Without documentation standards, deliverables lack the documentation needed for maintenance and handover.",
    severity: "medium",
    likelihood: "common",
    impact: "Undocumented systems creating maintenance dependency and knowledge loss.",
    detection_guidance: "Check for documentation requirements: technical docs, user guides, API documentation, architecture diagrams, and runbooks.",
    remediation: "Include documentation requirements: technical architecture docs, API documentation (OpenAPI), user guides, runbooks, and acceptance criteria for docs.",
    real_world_impact: null
  },
  {
    id: "op-no-capacity-reservation-for-peak",
    name: "No Capacity Reservation for Peak Periods",
    risk_category: "operational",
    clause_type: "sla",
    trigger: "Service contract with known peak periods without reserved capacity provisions",
    description: "Without reserved capacity, service degrades during predictable peak periods when resources are shared.",
    severity: "medium",
    likelihood: "occasional",
    impact: "Service degradation during critical business peak periods.",
    detection_guidance: "Check for peak capacity provisions: reserved capacity, burst provisions, and SLA modifications during known peak periods.",
    remediation: "Include peak capacity reservation: define peak periods, reserve 150% of baseline capacity, and SLA applies equally during peak.",
    real_world_impact: null
  },
  {
    id: "reg-no-supply-chain-due-diligence",
    name: "No Supply Chain Due Diligence (CSDDD)",
    risk_category: "regulatory",
    clause_type: "esg-human-rights-dd",
    trigger: "Supply chain contract without corporate sustainability due diligence obligations per EU CSDDD",
    description: "EU Corporate Sustainability Due Diligence Directive requires supply chain human rights and environmental due diligence.",
    severity: "high",
    likelihood: "common",
    impact: "CSDDD non-compliance fines up to 5% of global turnover; civil liability for harm.",
    detection_guidance: "For material suppliers, check for CSDDD provisions: human rights due diligence, environmental due diligence, and remediation obligations.",
    remediation: "Include CSDDD provisions: human rights assessment, environmental due diligence, corrective action plans, and termination as last resort.",
    real_world_impact: null
  },
  {
    id: "reg-no-digital-euro-preparation",
    name: "No Digital Euro Preparation",
    risk_category: "regulatory",
    clause_type: "compliance",
    trigger: "Payment services contract without provisions for future digital euro acceptance requirements",
    description: "EU digital euro regulation will require basic merchants to accept digital euro payments.",
    severity: "low",
    likelihood: "rare",
    impact: "Non-compliance with digital euro acceptance obligation when enacted.",
    detection_guidance: "For payment service contracts, check for future-proofing: digital euro readiness clause, technology update obligations, and regulatory change mechanism.",
    remediation: "Include regulatory future-proofing clause: technology update for digital euro when required, cost allocation, and implementation timeline.",
    real_world_impact: null
  },
  {
    id: "cpl-no-anti-counterfeiting-provisions",
    name: "No Anti-Counterfeiting Provisions",
    risk_category: "compliance",
    clause_type: "compliance",
    trigger: "Product supply contract without anti-counterfeiting measures and verification obligations",
    description: "Counterfeit products in supply chains create safety, regulatory, and reputational risks.",
    severity: "high",
    likelihood: "occasional",
    impact: "Product recalls; regulatory penalties; personal injury liability from counterfeit components.",
    detection_guidance: "For product supply contracts, check for anti-counterfeiting: authentication measures, traceability, testing, and indemnification.",
    remediation: "Include anti-counterfeiting clause: authentication measures, serialisation/traceability, incoming goods testing, and counterfeit component indemnification.",
    real_world_impact: null
  },
  {
    id: "con-no-limitation-on-recourse",
    name: "No Limitation on Recourse for Non-Recourse Obligations",
    risk_category: "contractual",
    clause_type: "liability",
    trigger: "Project finance or SPV contract without clear non-recourse provisions",
    description: "Without non-recourse language, sponsors may face unexpected personal liability for SPV obligations.",
    severity: "critical",
    likelihood: "occasional",
    impact: "Personal liability of sponsors for SPV debts and obligations.",
    detection_guidance: "For SPV or project finance structures, check for non-recourse provisions, carve-outs, and comfort letter boundaries.",
    remediation: "Include clear non-recourse provision: obligations limited to SPV assets, defined carve-outs (fraud, misrepresentation), and no pierce of corporate veil.",
    real_world_impact: null
  },
  {
    id: "con-no-power-of-attorney-controls",
    name: "No Controls on Powers of Attorney",
    risk_category: "contractual",
    clause_type: "representations-authority",
    trigger: "Contract granting power of attorney without scope limitations, expiry, and revocation rights",
    description: "Broad PoA grants without controls allow agent to bind principal to unintended obligations.",
    severity: "high",
    likelihood: "occasional",
    impact: "Principal bound to obligations not authorised or intended.",
    detection_guidance: "Check for PoA controls: defined scope, expiry date, revocation rights, and reporting obligations.",
    remediation: "Limit PoA to specific transactions, include automatic expiry date, require monthly reporting, and preserve immediate revocation right.",
    real_world_impact: null
  },
  {
    id: "ip-no-ai-model-ownership-allocation",
    name: "No AI Model Ownership Allocation",
    risk_category: "ip",
    clause_type: "ai-output-ownership",
    trigger: "Custom AI model development contract without ownership allocation for trained models",
    description: "Custom-trained AI models represent significant investment; ownership must be explicitly allocated.",
    severity: "critical",
    likelihood: "common",
    impact: "Disputed ownership of custom-trained models costing EUR 100K-1M+ to develop.",
    detection_guidance: "Check for model ownership: base model vs fine-tuned weights, training data contribution, and model portability rights.",
    remediation: "Customer owns fine-tuned model weights and training data contributions. Provider retains base model. Include model export rights in standard formats.",
    real_world_impact: null
  },
  {
    id: "dp-no-data-residency-for-ai-inference",
    name: "No Data Residency for AI Inference Processing",
    risk_category: "data-protection",
    clause_type: "ai-data-residency",
    trigger: "AI service contract where inference API calls may be routed to non-EU data centres",
    description: "AI inference requests containing personal data may be processed in non-EU locations without adequate safeguards.",
    severity: "high",
    likelihood: "common",
    impact: "GDPR violations from personal data in inference requests processed outside EEA.",
    detection_guidance: "Check if AI inference API requests are processed exclusively in EU. Verify data flow for prompts, completions, and logging.",
    remediation: "Require EU-only inference processing, contractual data residency guarantee, no prompt logging outside EU, and data flow documentation.",
    real_world_impact: null
  },
  {
    id: "cont-no-warm-standby-for-critical",
    name: "No Warm Standby for Critical Applications",
    risk_category: "continuity",
    clause_type: "sla",
    trigger: "Critical application contract with cold DR only (no warm standby or active-passive failover)",
    description: "Cold DR requires hours of recovery time; critical applications need warm standby for rapid failover.",
    severity: "high",
    likelihood: "occasional",
    impact: "RTO of 4-24 hours for cold DR vs minutes for warm standby on critical applications.",
    detection_guidance: "For critical applications (RTO <1 hour), check for warm standby or active-passive architecture with automated failover.",
    remediation: "Require warm standby with automated failover for critical applications: <15-minute RTO, <5-minute RPO, and quarterly failover testing.",
    real_world_impact: null
  },
  {
    id: "rep-no-social-media-crisis-response",
    name: "No Social Media Crisis Response Protocol",
    risk_category: "reputational",
    clause_type: "sla",
    trigger: "Brand-facing service contract without social media crisis response coordination",
    description: "Service incidents amplified on social media require coordinated response within minutes, not hours.",
    severity: "medium",
    likelihood: "common",
    impact: "Viral reputational damage from uncoordinated social media response to service incidents.",
    detection_guidance: "Check for social media crisis protocol: monitoring, coordinated response, approved messaging, and escalation triggers.",
    remediation: "Include social media protocol: real-time monitoring, coordinated response within 30 minutes, pre-approved holding statements, and executive escalation.",
    real_world_impact: null
  },
  {
    id: "env-no-biodiversity-net-gain",
    name: "No Biodiversity Net Gain Obligation",
    risk_category: "environmental",
    clause_type: "esg-biodiversity",
    trigger: "Development contract in England without mandatory 10% biodiversity net gain from February 2024",
    description: "Environment Act 2021 requires 10% biodiversity net gain for most developments in England.",
    severity: "high",
    likelihood: "occasional",
    impact: "Planning refusal or enforcement from failure to achieve mandatory BNG.",
    detection_guidance: "For England developments, check for BNG plan: baseline assessment, 10% net gain calculation, 30-year management plan, and monitoring.",
    remediation: "Include BNG clause: pre-development baseline, 10% net gain plan, 30-year management and monitoring, and financial security for long-term management.",
    real_world_impact: null
  },
  {
    id: "fin-no-restitution-on-rescission",
    name: "No Restitution Provisions on Contract Rescission",
    risk_category: "financial",
    clause_type: "liability",
    trigger: "Contract without provisions for restitution and unwinding if the contract is rescinded",
    description: "Rescission requires parties to return to pre-contract position; without provisions, unwinding is costly and disputed.",
    severity: "medium",
    likelihood: "rare",
    impact: "Disputed unwinding costs and incomplete restitution on contract rescission.",
    detection_guidance: "Check for rescission/unwinding provisions: return of property, payment adjustments, IP reversion, and confidential information return.",
    remediation: "Include unwinding provisions: mutual return of property within 30 days, pro-rata payment adjustment, IP reversion, and data return/destruction.",
    real_world_impact: null
  },
  {
    id: "op-no-end-user-support-standards",
    name: "No End-User Support Standards",
    risk_category: "operational",
    clause_type: "sla",
    trigger: "Software service contract without defined end-user support standards and escalation",
    description: "Without support standards, users experience inconsistent quality and long resolution times.",
    severity: "medium",
    likelihood: "common",
    impact: "User productivity loss from poor support; user adoption decline.",
    detection_guidance: "Check for support standards: channels (phone, email, chat), hours, response times, resolution targets, and escalation path.",
    remediation: "Include support standards: multi-channel support, business hours minimum, P1 response in 15 minutes, 80% first-call resolution, and escalation path.",
    real_world_impact: null
  },
  {
    id: "cpl-no-sarbanes-oxley-controls",
    name: "No SOX Controls for US-Listed Entity",
    risk_category: "compliance",
    clause_type: "compliance",
    trigger: "Service contract with US-listed entity without SOX-relevant internal control provisions",
    description: "US-listed entities must ensure service providers support SOX internal control requirements.",
    severity: "high",
    likelihood: "occasional",
    impact: "SOX material weakness; SEC enforcement; auditor qualification.",
    detection_guidance: "For contracts with US-listed entities, check for SOX provisions: internal controls, SOC 1/2 reporting, and access to audit evidence.",
    remediation: "Include SOX clause: maintain internal controls, provide annual SOC 1 Type II report, cooperate with external auditors, and report control failures.",
    real_world_impact: null
  },
  {
    id: "op-no-zero-day-response-capability",
    name: "No Zero-Day Vulnerability Response Capability",
    risk_category: "operational",
    clause_type: "sla",
    trigger: "Critical infrastructure contract without zero-day vulnerability response provisions",
    description: "Zero-day vulnerabilities require emergency response outside normal patch management cycles.",
    severity: "critical",
    likelihood: "occasional",
    impact: "Extended exposure to actively exploited zero-day vulnerabilities.",
    detection_guidance: "Check for zero-day response: emergency patch capability, temporary mitigation deployment, and communication protocol.",
    remediation: "Require zero-day response: 4-hour mitigation for critical zero-days, emergency patch within 48 hours, and customer notification within 1 hour.",
    real_world_impact: "Log4Shell, MOVEit, and other zero-days required emergency response outside normal patch cycles."
  },
  {
    id: "reg-no-gdpr-one-stop-shop-coordination",
    name: "No GDPR One-Stop-Shop Coordination",
    risk_category: "regulatory",
    clause_type: "data-protection-processing-instructions",
    trigger: "Cross-border processing arrangement without coordination of lead supervisory authority",
    description: "Cross-border processing requires identification of lead DPA for consistency mechanism coordination.",
    severity: "medium",
    likelihood: "occasional",
    impact: "Multi-DPA investigations and conflicting decisions from uncoordinated regulatory engagement.",
    detection_guidance: "For cross-border processing, check for lead DPA identification, main establishment documentation, and regulatory cooperation obligations.",
    remediation: "Identify lead DPA based on main establishment, document basis for determination, and include cooperation obligations for regulatory inquiries.",
    real_world_impact: null
  },
  {
    id: "fin-no-clawback-for-misrepresentation",
    name: "No Clawback for Material Misrepresentation",
    risk_category: "financial",
    clause_type: "representations-accuracy-information",
    trigger: "Contract without clawback mechanism for payments made based on material misrepresentations",
    description: "Without clawback rights, payments made based on false representations cannot be efficiently recovered.",
    severity: "high",
    likelihood: "occasional",
    impact: "Inability to recover payments made based on false information without litigation.",
    detection_guidance: "Check for clawback provisions: trigger events (misrepresentation, fraud), recovery mechanism, timeframe, and set-off rights.",
    remediation: "Include clawback clause: automatic right to recover payments made based on material misrepresentation, set-off against future payments, and interest.",
    real_world_impact: null
  },
  {
    id: "con-no-governing-law-for-ip",
    name: "No IP-Specific Governing Law Consideration",
    risk_category: "contractual",
    clause_type: "governing-law-choice",
    trigger: "IP-intensive international contract without consideration of IP-specific jurisdictional issues",
    description: "IP rights are territorial; governing law choice may not address registration, enforcement, and infringement in key jurisdictions.",
    severity: "medium",
    likelihood: "occasional",
    impact: "Unenforceable IP provisions in key jurisdictions; gaps in territorial protection.",
    detection_guidance: "For IP-intensive international contracts, check if governing law adequately covers IP registration, enforcement, and infringement in all relevant territories.",
    remediation: "Include IP-specific jurisdiction provisions: registration territories, enforcement jurisdiction, and local counsel engagement for key markets.",
    real_world_impact: null
  },
  {
    id: "env-no-end-of-life-product-obligations",
    name: "No End-of-Life Product Environmental Obligations",
    risk_category: "environmental",
    clause_type: "esg-circular-economy",
    trigger: "Product supply contract without end-of-life environmental management obligations",
    description: "WEEE, battery regulations, and circular economy requirements impose take-back and recycling obligations.",
    severity: "medium",
    likelihood: "common",
    impact: "Non-compliance with WEEE/battery regulations; disposal cost liability.",
    detection_guidance: "For electronic or battery product supply, check for WEEE compliance, battery regulation compliance, take-back obligations, and recycling targets.",
    remediation: "Include end-of-life clause: WEEE registration, battery regulation compliance, take-back scheme, and recycling rate targets.",
    real_world_impact: null
  },
  {
    id: "op-no-continuous-improvement-obligation",
    name: "No Continuous Improvement Obligation",
    risk_category: "operational",
    clause_type: "sla",
    trigger: "Long-term service contract without continuous improvement and innovation obligations",
    description: "Without continuous improvement, service quality stagnates while market expectations advance.",
    severity: "low",
    likelihood: "common",
    impact: "Service quality falling behind market standards over multi-year terms.",
    detection_guidance: "For contracts >2 years, check for continuous improvement: annual improvement targets, innovation sharing, and technology refresh.",
    remediation: "Include continuous improvement: annual 3-5% efficiency targets, technology refresh obligations, innovation sharing, and benchmark comparison.",
    real_world_impact: null
  },
  {
    id: "fin-no-reverse-break-fee",
    name: "No Reverse Break Fee in M&A",
    risk_category: "financial",
    clause_type: "ma-conditions-precedent",
    trigger: "M&A transaction with buyer walk-away right but no reverse break fee to protect seller",
    description: "Without reverse break fee, seller bears full deal costs and opportunity cost if buyer walks away.",
    severity: "high",
    likelihood: "occasional",
    impact: "Seller bears EUR 200K-5M in deal costs and lost alternative opportunities.",
    detection_guidance: "Check for reverse break fee: buyer failure to close triggers payment to seller, typically 3-5% of deal value.",
    remediation: "Include reverse break fee of 3-5% of deal value for buyer walk-away, triggered by failure to close by long-stop date without regulatory cause.",
    real_world_impact: null
  },
  {
    id: "dp-no-data-ethics-framework",
    name: "No Data Ethics Framework for Analytics",
    risk_category: "data-protection",
    clause_type: "data-protection-processing-instructions",
    trigger: "Advanced analytics or AI contract without data ethics framework and review process",
    description: "Legal compliance alone does not prevent ethical harms from data analytics; ethical framework provides additional safeguards.",
    severity: "medium",
    likelihood: "occasional",
    impact: "Ethical harms from analytics creating reputational and legal exposure beyond GDPR compliance.",
    detection_guidance: "Check for data ethics provisions: ethics review process, prohibited uses, fairness assessment, and transparency commitment.",
    remediation: "Include data ethics framework: ethics review for high-impact analytics, prohibited use cases, fairness testing, and annual ethics audit.",
    real_world_impact: null
  },
  {
    id: "cont-no-digital-asset-recovery",
    name: "No Digital Asset Recovery Plan",
    risk_category: "continuity",
    clause_type: "termination",
    trigger: "Contract without provisions for recovery of digital assets (domains, certificates, API keys, accounts)",
    description: "Digital assets controlled by service providers become inaccessible if not explicitly addressed in termination.",
    severity: "high",
    likelihood: "common",
    impact: "Loss of access to domains, certificates, cloud accounts, and API keys on provider termination.",
    detection_guidance: "Check for digital asset inventory and recovery: domains, SSL certificates, cloud accounts, API keys, social media, and code repositories.",
    remediation: "Include digital asset schedule: inventory of all assets, customer ownership documentation, transfer procedures, and 30-day recovery timeline.",
    real_world_impact: null
  },
  {
    id: "reg-no-ai-liability-directive-compliance",
    name: "No AI Liability Directive Compliance",
    risk_category: "regulatory",
    clause_type: "ai-liability-allocation",
    trigger: "AI system contract without provisions addressing EU AI Liability Directive requirements",
    description: "EU AI Liability Directive introduces presumption of causality and disclosure obligations for AI harm.",
    severity: "high",
    likelihood: "occasional",
    impact: "Reversed burden of proof for AI-caused harm; mandatory evidence disclosure obligations.",
    detection_guidance: "Check for AI liability provisions: evidence preservation, disclosure obligations, causality documentation, and insurance coverage.",
    remediation: "Include AI liability clause: evidence preservation obligations, disclosure cooperation, incident documentation, and adequate liability insurance.",
    real_world_impact: null
  },
  {
    id: "con-no-escrow-for-source-code",
    name: "No Source Code Escrow for Custom Software",
    risk_category: "contractual",
    clause_type: "ip",
    trigger: "Custom software development contract without source code escrow for business continuity",
    description: "Without source code escrow, customer cannot maintain or modify software if developer ceases to operate.",
    severity: "high",
    likelihood: "occasional",
    impact: "Complete loss of ability to maintain business-critical custom software.",
    detection_guidance: "For custom software, check for source code escrow: independent agent, regular deposits, release triggers, and verification.",
    remediation: "Require source code escrow: independent agent, quarterly deposits with verification, release triggers (insolvency, material breach, cessation), and licence to use.",
    real_world_impact: null
  }
];
